/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {Audit} from './audit.js';
import * as i18n from '../lib/i18n/i18n.js';
import {ElementTimings as ComputedElementTimings} from '../computed/element-timings.js';


const UIStrings = {
  /** Title of a Lighthouse audit that provides details on any timestamps generated by the page. Element Timing refers to the 'Element Timing API', which contain render timing information for image and text node elements the developer annotated with an elementtiming attribute for observation*/
  title: 'Element Timing',
  /** Description of a Lighthouse audit that shows element timing information for elements marked with elementtiming attribute. This is displayed after a user expands the section to see more. No character length limits. The last sentence starting with 'Learn' becomes link text to additional documentation. */
  description:
    'These are the elements on the page that have timing information captured via the ' +
    'Element Timing API. Elements must have the elementtiming attribute to be measured. ' +
    '[Learn more about Element Timing API](https://web.dev/articles/custom-metrics#element_timing_api).',
  displayValue: `{itemCount, plural,
    =1 {1 element timing}
    other {# element timings}
    }`,
  columnElementId: 'Element ID',
  columnLoadTime: 'Load Time',
};

const str_ = i18n.createIcuMessageFn(import.meta.url, UIStrings);

class ElementTimings extends Audit {
  /**
   * @return {LH.Audit.Meta}
   */
  static get meta() {
    return {
      id: 'element-timings',
      title: str_(UIStrings.title),
      description: str_(UIStrings.description),
      scoreDisplayMode: Audit.SCORING_MODES.INFORMATIVE,
      guidanceLevel: 2,
      requiredArtifacts: ['Trace', 'TraceElements'],
    };
  }

  /**
   * @param {LH.Artifacts} artifacts
   * @param {LH.Audit.Context} context
   * @return {Promise<LH.Audit.Product>}
   */
  static async audit(artifacts, context) {
    const trace = artifacts.Trace;
    const elementTimings = await ComputedElementTimings.request(trace, context);
    const traceElements = artifacts.TraceElements;


    /** @type {LH.Audit.Details.Table['headings']} */
    const headings = [{key: 'node', valueType: 'node', label: str_(i18n.UIStrings.columnElement)}];

    const items = elementTimings.map(timing => {
      const element = traceElements.find(t => t.nodeId === timing.nodeId);

      const node = element ? Audit.makeNodeItem(element.node) :
      /** @type {LH.Audit.Details.TextValue} */ ( {type: 'text', value: timing.elementId});

      return {node, loadTime: timing.loadTime};
    });

    const details = Audit.makeTableDetails(headings, items);

    let displayValue;
    if (items.length) {
      displayValue = str_(UIStrings.displayValue, {
        itemCount: items.length,
      });
    }

    return {
      score: Number(elementTimings.length === 0),
      notApplicable: elementTimings.length === 0,
      displayValue,
      details,
    };
  }
}

export default ElementTimings;
export {UIStrings};
